<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="qa.marm.test.Authorization" tests="1" time="14.014" ignored="4" failures="0" timestamp="14 мар 2018 14:17:55 GMT" skipped="0" hostname="user-System-Product-Name" errors="1">
  <testcase name="Login" time="14.014" classname="qa.marm.test.Authorization">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at qa.marm.test.Authorization.Login(Authorization.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- Login -->
  <testcase name="ChangeTheTextOfTheVisualElement" classname="qa.marm.test.ButtonTest">
    <skipped/>
  </testcase> <!-- ChangeTheTextOfTheVisualElement -->
  <testcase name="ChangeTheVisibilityOfTheVisualElement" classname="qa.marm.test.ButtonTest">
    <skipped/>
  </testcase> <!-- ChangeTheVisibilityOfTheVisualElement -->
  <testcase name="AligningTheTextOfTheVisualElement" classname="qa.marm.test.ButtonTest">
    <skipped/>
  </testcase> <!-- AligningTheTextOfTheVisualElement -->
  <testcase name="CheckMainButton" classname="qa.marm.test.ButtonTest">
    <skipped/>
  </testcase> <!-- CheckMainButton -->
</testsuite> <!-- qa.marm.test.Authorization -->
